namespace Sharpmake.Generators.Ninja
{
    public partial class NinjaGenerator
    {
        public static class Template
        {
            private static string NewLine = System.Environment.NewLine;

            public static string Header =
@"# Generated by Sharpmake -- Do not edit!
";
            public static string SubNinja = $"subninja [projectFile] {NewLine}";
            public static string Include = $"include [projectFile] {NewLine}";
        }
    }
}
